# Site settings
title: Abhishek Kumar
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
 url: "https://abhishek63.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Abhishek Kumar
user_description: I am a Computer Science undergrade student at Haldia Institute of Technology, currently in Final year. Currently, I am actively seeking a part-time software engineering role(Specialy Web Development) anywhere around the globe to add more value to my Resume. Peer Group, Work Quality and Growth Opportunities are the most important things I am looking for in a job.
user_title: Software Developer
email: kumargolu63@gmail.com
twitter_username: https://twitter.com/kumargolu63?lang=en
github_username:  https://github.com/abhishek63
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
